# /home/tokosan/.config/tmuxinator/config.yml

name: config
root: ~/

windows:
  - nvim:
    - cd ~/.config/nvim
    - nvim init.lua
  - tmux:
    - cd ~/.config/tmux/
    - nvim tmux.conf
  - bash:
    - config-bash
  - system:
    - cd ~/.config/
    - nvim .
  - dotfiles:
    - cd ~/dotfiles/
    - nvim .
  - tmuxinator:
    - cd ~/.config/tmuxinator/
    - nvim .
  - git:
    - cd ~/dotfiles
    - lazygit
